[bar.default]
bottom = true

# dimensions in pixels
width = 1200
height = 50

# horizontal center
center = true

# offsets will be applied
# on top of `center` if
# it's enabled
offset-x = 0
offset-y = -10

widgets = [
	"hello-world"
]

# can be around, between, none
widget-spacing = "around"

# color in hex
background-color = "#000000"

[widgets.hello-world]
type = "text"
text = "Hello World!"
font = "DejaVu Sans Mono"

# must be a floating-point number
# TODO: auto into this
font-size = 13.0

# weight can be italic, oblique, bold, normal
# slant can be TODO
font-style = { weight = "bold", slant = "none" }

# color in hex
color = "#ffffff"
