[bar]
name = "main"
bottom = true

# dimensions in pixels
width = 1000
height = 50

# horizontal center
center = true

# offsets will be applied
# on top of `center` if
# it's enabled
offset-x = 0
offset-y = 0

widgets = [
	"clock"
]

# can be around, between, none
widget-spacing = "around"

# defaults to white and black
# respectively
foreground-normal = "#ffffff"
background-normal = "#1a2630"

# defaults to normals
foreground-hover = "#ffffff"
background-hover = "#1a2630"

[widgets.clock]
# built-in module
type = "time"
# strftime-style format
format = "%H:%M"

# defaults to white and black
# respectively
foreground-normal = "#ffffff"
background-normal = "#000000"

# defaults to normals
foreground-hover = "#ffffff"
background-hover = "#000000"
